const profileActionTypes={
    GET_PROFILE_SUCCESS:"GET_PROFILE_SUCCESS",
    GET_PROFILE_FAILURE:"GET_PROFILE_FAILURE",
    CLEAR_PROFILE:"CLEAR_PROFILE",
    UPDATE_PROFILE:"UPDATE_PROFILE",
    GET_ALL_PROFILES:"GET_ALL_PROFILES",
    GET_OTHERS_PROFILE:"GET_OTHERS_PROFILE",
    GET_REPOS:"GET_REPOS"
};

export default profileActionTypes;